### PR TITLE
Fix: page header

### LINKED ISSUE #18: [BUG] powered by on other pages than frontpage
## Summary
powered by section is visible on the search page:
grafik

and on publish page:
grafik

## Expected Behavior
powered by Ocean Protocol should only be visible on the frontpage for now.

## Fix:
- [ ] remove powered by from other pages

### PR DESCRIPTION
**Pull request by LucaMilanese90**
Fixes #18 

## Proposed Changes

  - show "powered" by section only on home page

### CODE REVIEW

File: src/components/templates/Page.tsx [hunk 1]
```diff
@@ -27,7 +27,7 @@ export default function Page({
           title={title}
           description={description}
           center={headerCenter}
-          powered
+          powered={uri === '/'}
```
Comment (oceanByte) [inline src/components/templates/Page.tsx:30]: suggestion(non-blocking): extracting to a variable like `isHome` might improve readability

**Review by oceanByte — APPROVED** [review]

**Review by oceanByte — APPROVED** [review]
