### PR TITLE
fix: refetch ctd history on page change

### LINKED ISSUE #324: [BUG] Retrieve results in profile/compute jobs links to wrong jobs
## Summary
When clicking on “show details” is brings up the wrong details.

## Current Behavior
see above
  
## Expected Behavior
Show Details is referencing the correct assets

## Steps to Reproduce

1. Open multi-page results, i.e. 0x4C84a36fCDb7Bc750294A7f3B5ad5CA8F74C4A52 as account with 5 pages
2. then cycle through the pages. 1 to 5, 5 to 2. 
3. then the wrong results are being delivered when you look at some cases.

### PR DESCRIPTION
**Pull request by LucaMilanese90**
Fixes #324

### CODE REVIEW

File: src/components/Profile/History/ComputeJobs/index.tsx [hunk 1]
```diff
@@ -17,17 +17,22 @@ export function Status({ children }: { children: string }): ReactElement {
 const columns: TableOceanColumn<ComputeJobMetaData>[] = [
   {
     name: 'Dataset',
-    selector: (row) => (
-      <AssetListTitle did={row.inputDID[0]} title={row.assetName} />
-    )
+    selector: (row) => {
+      console.log(row.assetName)
```
Comment (moritzkirstein) [inline src/components/Profile/History/ComputeJobs/index.tsx:21]: issue: remove console.log / use logger if needed

File: src/components/Profile/History/ComputeJobs/index.tsx [hunk 2]
```diff
@@ -17,17 +17,22 @@ export function Status({ children }: { children: string }): ReactElement {
...
   },
   {
     name: 'Network',
     selector: (row) => <NetworkName networkId={row.networkId} />
   },
   {
     name: 'Created',
-    selector: (row) => <Time date={row.dateCreated} isUnix relative />
+    selector: (row) => {
+      console.log(row.dateCreated)
```
Comment (moritzkirstein) [inline src/components/Profile/History/ComputeJobs/index.tsx:32]: issue: remove console.log or use logger

**Review by moritzkirstein — CHANGES_REQUESTED** [review]

**Review by moritzkirstein — APPROVED** [review]
