### PR TITLE
Fix: buy correct datatoken for compute job

### LINKED ISSUE #126: [BUG] Failed to start compute job
## Summary
In the asset detail page, selecting an algorithm and pressing on the "buy compute job" button sometimes leads to an error.

image

## Steps to Reproduce
1. select a dataset from the compute section
2. select an algorithm
3. quickly change your selection with another algorithm and press the "buy" button
  
## Proposed solution
Disable algorithm selection and show a loader until price fetch completion, this should avoid the problem.

### PR DESCRIPTION
**Pull request by LucaMilanese90**
Fixes #126

## Proposed Changes

  - disable algorithm asset list while fetching the selected algorithm price to avoid buying the wrong data token

### CODE REVIEW

File: src/components/organisms/AssetActions/Compute/PriceOutput.tsx [hunk 1]
```diff
@@ -62,35 +64,45 @@ export default function PriceOutput({
   hasPreviousOrderSelectedComputeAsset,
   hasDatatokenSelectedComputeAsset,
   algorithmPrice,
-  selectedComputeAssetTimeout
+  selectedComputeAssetTimeout,
+  loading
```
Comment (oceanByte) [inline src/components/organisms/AssetActions/Compute/PriceOutput.tsx:68]: nitpick(blocking): We should follow the convention for booleans here and use `isLoading` instead.

**Review by oceanByte — APPROVED** [review]

**Review by moritzkirstein — APPROVED** [review]
