### PR TITLE
Ffix: Update compute history to reflect v3 changes

### LINKED ISSUE #35: [BUG] Compute History result links are wrong
## Summary
Result links link to `https://portal.minimal-gaia-x.eu/[object Object]` but should link to the computation results and logs.

## Current Behavior
Link of compute results on the profile history page is wrong.
  
## Expected Behavior
Compute results are listed in history and available after signing.

### PR DESCRIPTION
**Pull request by moritzkirstein**
Fixes #35 

## Proposed Changes

  - update ocean.js
  - update compute history (especially `Results.tsx`)
  - refactoring

see also: https://github.com/oceanprotocol/market/pull/958

### CODE REVIEW

File: src/components/pages/Profile/History/ComputeJobs/Results.tsx [hunk 1]
```diff
@@ -40,74 +41,81 @@ export default function Results({
...
+        const computeService = ddo.findServiceByType('compute')
+        const jobStatus = await ocean.compute.status(
+          account,
+          job.did,
+          ddo,
+          computeService,
+          job.jobId
+        )
+        if (jobStatus) {
+          console.log('results', jobStatus)
```
Comment (oceanByte) [inline src/components/pages/Profile/History/ComputeJobs/Results.tsx:59]: thought(non-blocking): console logs should be removed for production. But I guess in this particular case it is reasonable as it is considered software in development.

File: src/components/pages/Profile/History/ComputeJobs/Details.tsx [hunk 2]
```diff
@@ -114,12 +114,12 @@ export default function Details({
             />
           )}
           <MetaItem title="Job ID" content={<code>{job.jobId}</code>} />
-          {job.resultsDid && (
+          {/* {job.resultsDid && (
             <MetaItem
               title="Published Results DID"
               content={<code>{job.resultsDid}</code>}
             />
```
Comment (oceanByte) [inline src/components/pages/Profile/History/ComputeJobs/Details.tsx:121]: thought(non-blocking): Comments should be removed in normal circumstances but since is rather a quick fix we can leave it as is.

**Review by oceanByte — APPROVED** [review]
